version: '3.4'

services:
  employeeapi:
    image: ${DOCKER_REGISTRY-}employeeapi
    build:
      context: .
      dockerfile: EmployeeAPI\Dockerfile 
    ports:
            - "5000:5000"
            - "5001:5001"

      
